### ISSUE TITLE
Role Assignment on Storage Account File share

### ISSUE THREAD

**Issue by gummigroda** [Azure/bicep-types-az#1532]

**Comment by alex-frankel** [comment]
If anyone here who has encountered the issue can open a support ticket to have this routed to the Storage Resource Provider team, that would be helpful.

**Comment by AlexanderSehr** [comment]
I just filed a support request as this also was raised in [CARML](https://github.com/Azure/ResourceModules/issues/4346) and would, if not handled end up in AVM. @alex-frankel I'll implement the workaround proposed by @brwilkinson for now, but sincerely hope this is fixed by the Storage PG. Inventing an artificial resource type 'fileShares' appears to be a major oversight on their part 🔧

**Comment by Mike-E-angelo** [comment]
I ran into this issue as well and see there was a PR by @AlexanderSehr 🙏  Has it made its way into Bicep or do I have something misunderstood (quite likely 😁)?  

FWIW I did try the workaround but am not having any luck with it.  It seems to execute but the Role Assignment is not listed in the share's assignments.  In my case I am wanting to add a Managed Identity, and I noticed the workaround is for a group.  I am curious if this is why this might not be working. 🤔

**Comment by AlexanderSehr** [comment]
> I ran into this issue as well and see there was a PR by @AlexanderSehr 🙏 Has it made its way into Bicep or do I have something misunderstood (quite likely 😁)?
> 
> FWIW I did try the workaround but am not having any luck with it. It seems to execute but the Role Assignment is not listed in the share's assignments. In my case I am wanting to add a Managed Identity, and I noticed the workaround is for a group. I am curious if this is why this might not be working. 🤔

You wish :D No, it was not yet fixed by the Provider and my support ticket is also still open. However - I did implement the workaround both in the [CARML](https://github.com/Azure/ResourceModules/blob/3243344acd6e25211e283dcd2f53eadf33ec43c0/modules/storage/storage-account/file-service/share/main.bicep#L79-L86), as well as the (to be) [Azure-Verified-Modules](https://github.com/Azure/bicep-registry-modules/pull/746) module if you want to have a reference and hope to get rid of the workaround as soon as I hear back from the Product Group.

**Comment by Mike-E-angelo** [comment]
Thank you for the clarification @AlexanderSehr.  FWIW I was able to get the workaround working after all. 😌  I had the wrong path/share used (lots of moving pieces over here), so I am set in the meantime.

Also, I did want to mention that in Visual Studio Code, using the above workaround does result in the following warning:

![image](https://github.com/Azure/bicep-types-az/assets/2931376/94b054b9-684f-4c65-baff-0cbc616a538d)

Interestingly enough the warning's URL resolves to here:
https://www.bing.com/?ref=aka&shorturl=bicep/linter/no-deployments-resources

Not sure if this is a bug, but thought I would mention it.  Please note that I am already in a module and wonder if this is contributing to this.

**Comment by AlexanderSehr** [comment]
> Thank you for the clarification @AlexanderSehr. FWIW I was able to get the workaround working after all. 😌 I had the wrong path/share used (lots of moving pieces over here), so I am set in the meantime.
> 
> Also, I did want to mention that in Visual Studio Code, using the above workaround does result in the following warning:
> 
> ![image](https://private-user-images.githubusercontent.com/2931376/296292190-94b054b9-684f-4c65-baff-0cbc616a538d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzcxMzcsIm5iZiI6MTcwNTA3NjgzNywicGF0aCI6Ii8yOTMxMzc2LzI5NjI5MjE5MC05NGIwNTRiOS02ODRmLTRjNjUtYmFmZi0wY2JjNjE2YTUzOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMTYyNzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRkMGZlMDE1YzUzNDY3ZTI3NGFkOGMyZTE1ZmQwYmMyOGJmMjFhMTEwOWY3YWU1Y2FmZjRhOTEyZTIwMjE3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gplsAOeh5J9mtomrEkq7TMFqk4CH83cgjVBghdHxu5g)
> 
> Interestingly enough the warning's URL resolves to here: https://www.bing.com/?ref=aka&shorturl=bicep/linter/no-deployments-resources
> 
> Not sure if this is a bug, but thought I would mention it. Please note that I am already in a module and wonder if this is contributing to this.

Nah, it's by design. `Microsoft.Resource/deployments` is now 'hidden' behind the `module myModule 'localPath/main.bicep' = { (...) }` syntax. So if you use local references you'll see they in the rendered ARM template they're all just deployment objects that correspond in turn to deployment objects in the Azure Portal. However, in this case you're ferefencing a nested linked ARM template so you don't really get around it. You can supress it though.

**Comment by A7exSchin** [comment]
There might be a possible relation to another issue I am facing currently:

I want a cluster to have access to a storage account file share. When I assign the role "Storage File Data Privileged Contributor" it gets assigned the permissions

```
"Microsoft.Storage/storageAccounts/fileServices/fileshares/files/read",
"Microsoft.Storage/storageAccounts/fileServices/fileshares/files/write",
"Microsoft.Storage/storageAccounts/fileServices/fileshares/files/delete",
```

however, on access it throws an error that the object does not have the permission

`'Microsoft.Storage/storageAccounts/fileServices/shares/read'`

So it seems the scope is bugged/named wrong. Seems like such an easy fix, or do I misunderstand that?

**Comment by anthony-c-martin** [comment]
The link https://aka.ms/bicep/linter/no-deployments-resources has been fixed to correctly redirect to Microsoft Docs.

The linter rule is valid here - instead of:
```bicep
resource ResourceRoleAssignmentUsers 'Microsoft.Resources/deployments@2021-04-01' = {
  name: 'user-permissions_${now}'
  properties: {
    mode: 'Incremental'
    expressionEvaluationOptions: {
      scope: 'Outer'
    }
    template: json(loadTextContent('./genericRoleAssignment.json'))
    parameters: {
      scope: {
        value: replace(fileshare.id, '/shares/','/fileshares/')
      }
      name: {
        value: guid('${subscription().id},${resourceGroup().id},${stg.name},${fileshare.name},-users')
      }
      roleDefinitionId: {
        value: '0c867c2a-1d8c-454a-a3db-ab2ea1bdc8bb' // Storage File Data SMB Share Contributor
      }
      principalId: {
        value: genSettings.AADGroup
      }
      principalType: {
        value: 'Group'
      }
    }
  }
}
```

The recommendation is to use:
```bicep
module ResourceRoleAssignmentUsers 'genericRoleAssignment.json' = {
  name: 'user-permissions_${now}'
  params: {
    scope: replace(fileshare.id, '/shares/','/fileshares/')
    name: guid('${subscription().id},${resourceGroup().id},${stg.name},${fileshare.name},-users')
    roleDefinitionId: '0c867c2a-1d8c-454a-a3db-ab2ea1bdc8bb' // Storage File Data SMB Share Contributor
    principalId: genSettings.AADGroup
    principalType: 'Group'
  }
}
```

**Comment by BronsonMagnan** [comment]
Hello from June 2024, this is still an issue. and I spent an entire day of troubleshooting before I noticed /shares/ <> /fileshares/.  The work around with calling the arm from inside bicep does the trick though.

**Comment by roggypro** [comment]
> Hello from June 2024, this is still an issue. and I spent an entire day of troubleshooting before I noticed /shares/ <> /fileshares/. The work around with calling the arm from inside bicep does the trick though.

Same with me in October 2024.

**Comment by gstephenhr** [comment]
Hitting this December 2024

https://github.com/Azure/azure-rest-api-specs/issues/24568

**Comment by mrkesu** [comment]
Two and a half years later and this simple bug has still not been fixed. Incredible, especially considering we pay for this resource type.

**Comment by Mike-E-angelo** [comment]
If only maximizing shareholder value meant improving the quality of code @mrkesu 🙄

**Comment by nitinitare** [comment]
Running into same issue in April 2025, still no fix for the issue.

**Comment by poorleno1** [comment]
I can confirm that the same issue when using terraform.

**Comment by Abhi7739309** [comment]
sbm approvaLS
